# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Treat missing required parameters as errors
    missing_required_param: error
    # Treat unused local variables as warnings
    unused_local_variable: warning
    # Treat unused imports as warnings for cleaner code
    unused_import: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  rules:
    # Performance-related lints
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    unnecessary_brace_in_string_interps: true
    avoid_redundant_argument_values: true
    
    # Code quality lints
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_print: true
    avoid_empty_else: true
    avoid_returning_null_for_future: true
    cancel_subscriptions: true
    close_sinks: true
    
    # Best practices
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_contains: true
    prefer_if_null_operators: true
    prefer_null_aware_operators: true
    use_string_buffers: true
    
    # Widget performance
    avoid_function_literals_in_foreach_calls: true
    prefer_foreach: true
    sort_child_properties_last: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
