// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-3S8eV-GN0JnleFOhf2G5zh9LqMgL4Ow',
    appId: '1:10666150647:web:4d1066ffe7304904dd21f2',
    messagingSenderId: '10666150647',
    projectId: 'titipin-app',
    authDomain: 'titipin-app.firebaseapp.com',
    storageBucket: 'titipin-app.firebasestorage.app',
    measurementId: 'G-187B2BNXD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANtAYIFwXSn3keJg1ffwDNvWCfvI1XueI',
    appId: '1:10666150647:android:549086564bff8059dd21f2',
    messagingSenderId: '10666150647',
    projectId: 'titipin-app',
    storageBucket: 'titipin-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWUs0n7r5ylrubQyKE7ETEykDuKN50a1k',
    appId: '1:10666150647:ios:504916313749fd1edd21f2',
    messagingSenderId: '10666150647',
    projectId: 'titipin-app',
    storageBucket: 'titipin-app.firebasestorage.app',
    iosBundleId: 'com.example.tugasakhir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWUs0n7r5ylrubQyKE7ETEykDuKN50a1k',
    appId: '1:10666150647:ios:504916313749fd1edd21f2',
    messagingSenderId: '10666150647',
    projectId: 'titipin-app',
    storageBucket: 'titipin-app.firebasestorage.app',
    iosBundleId: 'com.example.tugasakhir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-3S8eV-GN0JnleFOhf2G5zh9LqMgL4Ow',
    appId: '1:10666150647:web:ac8c3c4c74a7fa59dd21f2',
    messagingSenderId: '10666150647',
    projectId: 'titipin-app',
    authDomain: 'titipin-app.firebaseapp.com',
    storageBucket: 'titipin-app.firebasestorage.app',
    measurementId: 'G-DZ54VHYL0E',
  );
}
